# Generated by Django 2.0.7 on 2018-09-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psdfile',
            name='h',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='psdfile',
            name='w',
            field=models.IntegerField(null=True),
        ),
    ]
