# Generated by Django 2.0.7 on 2018-09-27 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='work',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='cut',
        ),
        migrations.DeleteModel(
            name='KeyPoint',
        ),
        migrations.DeleteModel(
            name='PSDFile',
        ),
        migrations.DeleteModel(
            name='Cluster',
        ),
        migrations.DeleteModel(
            name='Instance',
        ),
    ]
