# Generated by Django 2.0.7 on 2018-10-02 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_auto_20180927_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.Work')),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('index', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Cluster')),
                ('cut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Cut')),
            ],
        ),
        migrations.CreateModel(
            name='KeyPoint',
            fields=[
                ('index', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('partnum', models.PositiveSmallIntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('visible', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PSDFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('datafile', models.FileField(upload_to='')),
                ('w', models.IntegerField(null=True)),
                ('h', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
